version: '3'
volumes:
  websocket_config:
  core_db:
  redis_data:
  
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - ./src:/app/src:z
      - ./public:/app/public:z
      - ./config:/app/config:z
      - ./vendor:/app/vendor:z
      - ./tests:/app/tests:z
      - ./composer.json:/app/composer.json:z
      - ./composer.lock:/app/composer.lock:z
      - ./.pomm_cli_bootstrap.php:/app/.pomm_cli_bootstrap.php:z
    links:
      - websocket
      - core-db
    networks:
      default:
      
  core-db:
    image: postgres:10-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discord_bot
    volumes:
      - core_db:/var/lib/postgresql/data:z
    networks:
      default:
      
  websocket:
    image: qbonaventure/discord-bot-ws
    expose:
      - "7632"
    tty: true
    restart: always
    volumes:
      - ./config:/app/config:z
    links: 
      - broker
      - cache
    networks:
      default:
      
  broker:
    image: rabbitmq:3.7-alpine
    expose:
      - "4369"
      - "5671"
      - "5672"
      - "25672"
    networks:
      default:
  cache:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data:z
    networks:
      default:
networks:
    default:
        driver: bridge
 
