<?php
/**
 * File generated by vendor/bin/apigility-upgrade-to-1.5.
 *
 * Original contents are available in config/modules.config.php.old
 */

return [
    'Zend\\Cache',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\I18n',
    'Zend\\Log',
    'Zend\\Mvc\\I18n',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Validator',
    'Zend\\Cache',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\I18n',
    'Zend\\Log',
    'Zend\\Mvc\\I18n',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Validator',
    'Zend\\Router',
    'ZF\\Apigility',
    'Application',
	'Aspects',
];
